language: python
services:
- postgresql
python:
- 3.4
env:
- DJANGO=2.0.3 DB=postgres

install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_db;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
