    language: python

    python:

      - "3.6"

    services:

      - postgresql

    env:

      -DJANGO=1.8 DB=postgresql
    install:

      - pip install -r requirements.txt

    before_script: 

      - psql -c 'create database travis_ci_test;' -U postgres
      - python3 manage.py makemigrations
      - python3 manage.py migrate
    script: # => 7

      - python3 manage.py test