language: python

python:
  - "3.4"

services: mysql

env:
  matrix:
    - DJANGO=1.7 DB=mysql

#commands to install dependencies
install:
- pip install -r requirements.txt

before_script:
- mysql -e 'create database IF NOT EXISTS myapp_db;' -uroot
- mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" -uroot
- python manage.py migrate


script:
- python manage.py test