# Generated by Django 2.0.3 on 2019-03-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('open_date', models.CharField(max_length=10)),
                ('close_date', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
