# Generated by Django 2.0.3 on 2019-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_idea',
            name='message',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
