# Generated by Django 2.0.3 on 2019-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190307_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_idea',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
