# Generated by Django 2.0.3 on 2019-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20190307_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_idea',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
