# Generated by Django 2.0.3 on 2019-03-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_trade_idea_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_idea',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trade_idea',
            name='upside',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
