# Generated by Django 2.0.3 on 2019-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20190307_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade_idea',
            name='performance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade_idea',
            name='upside',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
